version: "3.7"

services:
  backend:
    build: ./cookbook
    command: /usr/local/bin/gunicorn cookbook.wsgi:application -b 0.0.0.0:8000 --workers 1 --reload
    volumes:
      - ./cookbook:/app
    expose:
      - "8000"
    networks:
      - database
      - reverse-proxy
    env_file:
      - ./.env
    depends_on:
      - db

  client:
    build: ./client
    command: yarn serve
    volumes:
      - ./client:/app
    expose:
      - "8080"
    networks:
      - reverse-proxy
    depends_on:
      - backend

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    networks:
      - reverse-proxy
    depends_on:
      - backend
      - client

  db:
    image: postgres:12.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - database
    env_file:
      - ./.env.postgres

volumes:
  postgres_data:

networks:
  reverse-proxy:
  database:
