version: "3.7"

services:
  web-api:
    build: ./cookbook
    command: /usr/local/bin/gunicorn cookbook.wsgi:application -b 0.0.0.0:8000 --workers 1 --reload
    volumes:
      - ./cookbook:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  web-client:
    build: ./client
    command: yarn serve
    volumes:
      - ./client:/app
    ports:
      - 8080:8080
    depends_on:
      - web-api

  db:
    image: postgres:12.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.postgres

volumes:
  postgres_data:
