version: "3.7"

services:
  web-api:
    build:
      context: ./cookbook
      dockerfile: Dockerfile.prod
    command: gunicorn cookbook.wsgi:application --bind 0.0.0.0:8000
    expose: :
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:12.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.postgres.prod

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web-api

volumes:
  postgres_data:
