# Generated by Django 3.0.3 on 2020-04-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='kind',
            field=models.CharField(choices=[('Cuisine', 'Cuisine'), ('Meal', 'Meal'), ('Prep Method', 'Prep Method')], default='Meal', max_length=256),
            preserve_default=False,
        ),
    ]
