name: Server Tests

on:
  push:
    paths:
      - "cookbook/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt
      - name: Lint with pylint
        run: |
          # stop the build if there are pylint errors
          pylint --rcfile=.pylintrc --exit-zero cookbook/
      - name: Django tests
        run: |
          python cookbook/manage.py test recipe_manager.tests
